### ISSUE TITLE
Support for round-robin DNS

### ISSUE THREAD

**Issue by traktofon** [UCL-ARC/terraform-cloudflare-arc-dns#4]
According to [Cloudflare documentation](https://developers.cloudflare.com/dns/manage-dns-records/how-to/round-robin-dns/), round-robin DNS is achieved by adding multiple A records for the same name but with different IP addresses. A naive translation of this into the YAML scheme used here would result in something like

```yaml
gw.conjurer:
  value: "10.32.0.74"
  proxy: false
gw.conjurer:
  value: "10.32.0.75"
  proxy: false
```

Not sure how the Terraform YAML parser interprets this, but at least PyYAML sees this as a dictionary where the same key is defined twice, and it only retains one of the definitions. I suspect the same may happen in Terraform, or it might even complain about the duplicate key.

Can we support this use case?
